// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elghzhktubgeznyprtmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsZ2h6aGt0dWJnZXpueXBydG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTEwOTMsImV4cCI6MjA1OTg4NzA5M30.l5Srlu4ewvCmA48m4y-7K9ahikV0p0WIUeHZyoumOJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);